### ISSUE TITLE
Can't support RAML v1.0 ?

### ISSUE THREAD

**Issue by junxy** [raml2html/raml2md#12]
``` sh
$ raml2md Shop.raml
Error parsing: version validation
Unsupported RAML version: '#%RAML 1.0'
  in "Shop.raml", line 1, column 1:
    #%RAML 1.0
              ^
```

**Comment by kevinrenskers** [comment]
I'm sorry for that. Please read https://github.com/kevinrenskers/raml2html/issues/153 because raml2md has the same ownership / maintenance problem as raml2html.

**Comment by junxy** [comment]
Thanks for your reply ; )

**Comment by alexec** [comment]
+1

**Comment by PetarIvancevic** [comment]
+1

**Comment by kevinrenskers** [comment]
No need to +1, there is a beta with RAML 1 support available.
`npm install raml2md@4.0.0-beta1`

**Comment by kevinrenskers** [comment]
4.0.0 is released (no longer in beta)
