### ISSUE TITLE
subtemplate.nunjucks

### ISSUE THREAD

**Issue by freestylesolutions** [raml2html/raml2md#14]
I'm looking at subtemplate.nunjucks and see that it just contains a "B".
Am I missing something?

Are there some good examples out there of templates?

**Comment by kevinrenskers** [comment]
The actual main templates, not the ones in the examples folder.

**Comment by freestylesolutions** [comment]
I’m looking at the folder, this is what I see:

-rw-rw-r-- 1 ubuntu www-data  909745 Mar 17 22:45 github.raml
-rwxrwxr-x 1 ubuntu www-data    1375 Mar 17 22:45 item.handlebars
-rw-rw-r-- 1 ubuntu www-data    2933 Mar 17 22:45 keep-using-handlebars.js
-rwxrwxr-x 1 ubuntu www-data    9310 Mar 17 22:45 resource.handlebars
-rw-rw-r-- 1 ubuntu www-data    2357 Mar 17 22:45 script.js
-rwxrwxr-x 1 ubuntu www-data    7062 Mar 17 22:45 template.handlebars
-rw-rw-r-- 1 ubuntu www-data     355 Mar 17 22:45 unauthenticated.raml
-rw-rw-r-- 1 ubuntu www-data 1349229 Mar 17 22:45 github.html
-rw-rw-r-- 1 ubuntu www-data   54513 Mar 17 22:45 example.html
-rw-rw-r-- 1 ubuntu www-data  100072 Mar 17 22:45 example.png
-rw-rw-r-- 1 ubuntu www-data    7969 Mar 17 22:45 example.raml
drwxrwxr-x 3 ubuntu www-data    4096 Mar 17 22:45 custom-template-test

The main templates are template.handlebars?

Gary

**Comment by kevinrenskers** [comment]
Check https://github.com/raml2html/raml2md/tree/master/lib
